%%{init: {'theme': 'neutral'}}%%
    usecaseDiagram
    actor Customer
    actor Admin

    Customer --> (Browse Products)
    Customer --> (Add to Cart)
    Customer --> (Checkout)
    Customer --> (Make Payment)
    Customer --> (Write Review)

    Admin --> (Manage Products)
    Admin --> (Manage Orders)
    Admin --> (Manage Users)